### ISSUE TITLE
CameraGrabber crashes a lot.

### ISSUE THREAD

**Issue by utkarshsharma2922** [mtellect/CameraDeepAR#10]
### The camera crashes a lot . 

**Crash Report : **

F/libc    (18149): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x79 in tid 19453 (CameraHandlerTh), pid 18149 
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/m01qins/m01q:10/QP1A.190711.020/M015GXXU3AUC2:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2021-05-10 19:59:19+0530
pid: 18149, tid: 19453, name: CameraHandlerTh  >>> com.com.example.test.tbit <<<
uid: 10255
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x79
Cause: null pointer dereference
    r0  00000000  r1  00000001  r2  00000000  r3  00000000
    r4  c03b3700  r5  00000000  r6  8ee0b088  r7  8ee0b070
    r8  d8f09580  r9  a58d5d80  r10 c03b3b60  r11 00000500
    ip  a240fd9c  sp  8ee0b058  lr  a214d859  pc  a214d884
backtrace:
      #00  pc 0005f884  /data/app/com.com.example.test.tbit-bPe4qdM0uxYy4PETGUG30A==/lib/arm/libnative-lib.so (BuildId: 3b8b4b4adb1b349ff5d7c6a7087ab199bc4101eb)
      
      #01  pc 00053229  /data/app/com.com.example.test.tbit-bPe4qdM0uxYy4PETGUG30A==/lib/arm/libnative-lib.so (Java_ai_deepar_ar_DeepAR_frameUpdate+92) (BuildId: 3b8b4b4adb1b349ff5d7c6a7087ab199bc4101eb)
      
      #02 pc 000dc519  /apex/com.android.runtime/lib/libart.so (art_quick_generic_jni_trampoline+40) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #03 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #04 pc 00437275  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+252) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #05 pc 000dffeb  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+178) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #06 pc 00213925  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+280) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #07 pc 0020ff2d  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+552) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #08 pc 00430cd1  /apex/com.android.runtime/lib/libart.so (MterpInvokeDirectRange+220) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #09 pc 000d2c14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_direct_range+20) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #10 pc 0016daa6  [anon:dalvik-classes.dex extracted in memory from /data/app/com.com.example.test.tbit-bPe4qdM0uxYy4PETGUG30A==/base.apk] (ai.deepar.ar.DeepAR.receiveFrame+34)
      
      #11 pc 0042f439  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtualRange+964) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #12 pc 000d2b14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual_range+20) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #13 pc 0000383a  [anon:dalvik-classes11.dex extracted in memory from /data/app/com.com.example.test.tbit-bPe4qdM0uxYy4PETGUG30A==/base.apk!classes11.dex] (com.camera_deep_ar.CameraGrabber$CameraHandlerThread$2$1.onPreviewFrame+246)
      
      #14 pc 0042dc27  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1542) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #15 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #16 pc 0042a660  /system/framework/framework.jar (android.hardware.Camera$EventHandler.handleMessage+456)
      
      #17 pc 001eec29  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.9053038445767080447+192) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #18 pc 001f341b  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+126) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #19 pc 00420d5d  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+852) 
      (BuildId:9b79c57f3ed54b50283f74231a7e4048)
      
      #20 pc 000dc5a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) 
      (BuildId:9b79c57f3ed54b50283f74231a7e4048)
      
      #21 pc 0201f8c7  /memfd:/jit-cache (deleted) (android.os.Handler.dispatchMessage+134)
      
      #22 pc 020124ab  /memfd:/jit-cache (deleted) (android.os.Looper.loop+1194)
      
      #23 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #24 pc 00437389  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+248) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #25 pc 000dffff  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+198) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #26 pc 00213925  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+280) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #27 pc 0020f23d  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+716) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #28 pc 0042ea4d  /apex/com.android.runtime/lib/libart.so (MterpInvokeStatic+348) 
   (BuildId:9b79c57f3ed54b50283f74231a7e4048)
      
      #29 pc 000d2994  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_static+20) 
     (BuildId:9b79c57f3ed54b50283f74231a7e4048)
      
      #30 pc 003599fc  /system/framework/framework.jar (android.os.HandlerThread.run+56)
      
      #31 pc 001eec29  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.9053038445767080447+192) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #32 pc 001f341b  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+126) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #33 pc 00420d5d  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+852) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #34 pc 000dc5a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #35 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #36 pc 00437275  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+252) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #37 pc 000dffeb  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+178) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #38 pc 003781bb  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #39 pc 00378f43  /apex/com.android.runtime/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+306) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #40 pc 003aa4ef  /apex/com.android.runtime/lib/libart.so (art::Thread::CreateCallback(void*)+986) (BuildId: 9b79c57f3ed54b50283f74231a7e4048)
      
      #41 pc 000a7907  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) (BuildId: 6b958cfe24f2450b4242d6f7da7559ba)
      
      #42 pc 000611bf  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 6b958cfe24f2450b4242d6f7da7559ba)
      
Lost connection to device.

**Flutter doctor -v output **

Flutter (Channel stable, 2.0.6, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/mj/Documents/flutter
    • Framework revision 1d9032c7e1 (11 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    ! Xcode 12.0.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • SM M015G (mobile) • R9ZR1067HRJ • android-arm    • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 90.0.4430.93

**Comment by nimisane** [comment]
Did you find any solution I am facing the same issue?

**Comment by utkarshsharma2922** [comment]
I had to upgrade the sdk and then write platform specific code for iOS .

**Comment by mtellect** [comment]
Please check 0.0.2+2 and ReOpen if the issue persist
