### ISSUE TITLE
I try to get video path, but it don't know how ? onVideoRecorded doesn't return path

### ISSUE THREAD

**Issue by amalnaami** [mtellect/CameraDeepAR#12]

**Comment by whumpentertainment** [comment]
Hi @amalnaami  did you get black camera issue.

**Comment by amalnaami** [comment]
Hi @whumpentertainment
 I record video but it doesn't push me to another page to show it ang doesn't give me a path .
Do you have a path after you recording video

**Comment by whumpentertainment** [comment]
Yes i have path and i don't face any type of path issue. The only issue is black camera issues from back camera on second time.

**Comment by dannycortesv** [comment]
Hello i'm running the demo, but the onVideoRecorded doesn't triggered after i finish the video recording, any suggestion? Would be awesome if you continue supporting this plugin

**Comment by amosogra** [comment]
Android 10 this issue still remains
