### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by abdullah432** [mtellect/CameraDeepAR#14]

**Comment by Bac-Pham** [comment]
IDE run args/configuration
To set this up in your IDE of choice, you can use:

IntelliJ/Android Studio: "Edit Configurations" (in your run configurations) → "Additional run args".
VS Code: search for "Flutter run additional args" in your user settings.
In both cases, add --no-sound-null-safety.

<img width="1063" alt="Screen Shot 2021-09-06 at 14 23 14" src="https://user-images.githubusercontent.com/77664491/132176575-bb90449f-4a3f-45f3-87e4-a424c02c5404.png">

**Comment by mtellect** [comment]
Please check 0.0.2+2 and ReOpen if the issue persist
Added NullSafety Support
