### ISSUE TITLE
Execution failed for task ':camera_deep_ar:bundleDebugAar'.

### ISSUE THREAD

**Issue by trevster** [mtellect/CameraDeepAR#2]
Execution failed for task ':camera_deep_ar:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: /Users/trevin/Development/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/camera_deep_ar-0.0.1/android/libs/deepar.aar

 I've tried similar fixes by using the below snippet, but it still bugged.

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            // [required] camera_deep_ar
            url "${project(':camera_deep_ar').projectDir}/libs"
        }
    }
}

**Comment by Vvimal27** [comment]
> Execution failed for task ':camera_deep_ar:bundleDebugAar'.
> 
> > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: /Users/trevin/Development/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/camera_deep_ar-0.0.1/android/libs/deepar.aar
> 
> I've tried similar fixes by using the below snippet, but it still bugged.
> 
> allprojects {
> repositories {
> google()
> jcenter()
> maven {
> // [required] camera_deep_ar
> url "${project(':camera_deep_ar').projectDir}/libs"
> }
> }
> }

change gradle version to older one it works fine for ex. in build.gradle(in app module)
classpath 'com.android.tools.build:gradle:3.5.0 this version works fine

**Comment by apoorvpandey0** [comment]
> > Execution failed for task ':camera_deep_ar:bundleDebugAar'.
> > > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: /Users/trevin/Development/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/camera_deep_ar-0.0.1/android/libs/deepar.aar
> > 
> > 
> > I've tried similar fixes by using the below snippet, but it still bugged.
> > allprojects {
> > repositories {
> > google()
> > jcenter()
> > maven {
> > // [required] camera_deep_ar
> > url "${project(':camera_deep_ar').projectDir}/libs"
> > }
> > }
> > }
> 
> change gradle version to older one it works fine for ex. in build.gradle(in app module)
> classpath 'com.android.tools.build:gradle:3.5.0 this version works fine

Yes, this worked fine for me as well, but why is this issue occurring and how come this is not in the documentation. Someone should add this.

**Comment by trevster** [comment]
> > Execution failed for task ':camera_deep_ar:bundleDebugAar'.
> > > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: /Users/trevin/Development/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/camera_deep_ar-0.0.1/android/libs/deepar.aar
> > 
> > 
> > I've tried similar fixes by using the below snippet, but it still bugged.
> > allprojects {
> > repositories {
> > google()
> > jcenter()
> > maven {
> > // [required] camera_deep_ar
> > url "${project(':camera_deep_ar').projectDir}/libs"
> > }
> > }
> > }
> 
> change gradle version to older one it works fine for ex. in build.gradle(in app module)
> classpath 'com.android.tools.build:gradle:3.5.0 this version works fine

Thanks for the solution @Vvimal27

**Comment by jaisinghaniamit121** [comment]
> 3.5.0

Thank you so much !!

**Comment by rlee1990** [comment]
This doesn't fix the issue when using gradle version 4.1.2 because other packages are using a newer version

**Comment by Pratyaksh-hub** [comment]
someone found a better solution?

**Comment by KalanaPerera** [comment]
any solution?

**Comment by silentl007** [comment]
Any solution to this problem?

**Comment by KalanaPerera** [comment]
I've fixed this on my Fork, have a look, hope it helps. 

https://github.com/KalanaPerera/FlutterDeepAR

**Comment by silentl007** [comment]
> I've fixed this on my Fork, have a look, hope it helps.
> 
> https://github.com/KalanaPerera/FlutterDeepAR

Please how do i use it from your repo

**Comment by carman247** [comment]
@silentl007 

```
  camera_deep_ar: 
    git:
      url: https://github.com/KalanaPerera/FlutterDeepAR
```
