### ISSUE TITLE
MissingPluginException(No implementation found for method dispose on channel plugins.flutter.io/deep_ar_camera/0)

### ISSUE THREAD

**Issue by nimisane** [mtellect/CameraDeepAR#21]
When I navigate back to the screen where the CameraDeepAr widget is implemented I am getting the following error and then the app crashes

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found formethod dispose on channel plugins.flutter.io/deep_ar_camera/0)

**Comment by mtellect** [comment]
Fixed on Version 0.0.2+2
