### ISSUE TITLE
direct local .aar file dependencies are not supported when building an aar. flutter

### ISSUE THREAD

**Issue by MetaBoy8** [mtellect/CameraDeepAR#22]
I am using Flutter version : 2.5.3 and  Dart 2.14.4

camera_deep_ar: ^0.0.1

 "Cannot run with sound null safety" is the error message I get.

Please help me with this problem.

>> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: C:\Users\kuk\Documents\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\camera_deep_ar-0.0.1\android\libs\deepar.aar

**Comment by thoaipho51** [comment]
I also got the same error. Help..

**Comment by shah000** [comment]
i aslo got the same error ....Help me

**Comment by shah000** [comment]
Try this code working 100%
https://github.com/ortoniKC/flutter_deep_ar_face_effect

**Comment by Gunjan021** [comment]
I also got the same error. Help..

**Comment by Gunjan021** [comment]
> Try this code working 100% https://github.com/ortoniKC/flutter_deep_ar_face_effect

what did you do into this?

**Comment by mtellect** [comment]
Please check 0.0.2+2 and ReOpen if the issue persist

**Comment by mtellect** [comment]
Please check 0.0.2+2 and ReOpen if the issue persist
