### ISSUE TITLE
AAR Build broken

### ISSUE THREAD

**Issue by Samson11** [mtellect/CameraDeepAR#24]
:camera_deep_ar:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: 

I get this error when i add this plugin

**Comment by mtellect** [comment]
Set your class path in the project build.gradle to classpath 'com.android.tools.build:gradle:3.5.0'
