### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR

### ISSUE THREAD

**Issue by Bouchemel-Nasreddine** [mtellect/CameraDeepAR#26]
here is the output:
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: C:\Users\dell\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\camera_deep_ar-0.0.2+3\android\lib\deepar0.aar

**Comment by mtellect** [comment]
Related to https://github.com/mtellect/CameraDeepAR/issues/24#issue-1091689008
