### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR

### ISSUE THREAD

**Issue by nimisane** [mtellect/CameraDeepAR#34]
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the       
classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the     
Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file
dependencies of the :camera_deep_ar project caused this error:
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\camera_deep_ar-0.0.2+3\android\lib\deepar0.aar
[   +4 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 14m 44s

**Comment by filizsenturkndb** [comment]
dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
   
    }

use this in android/build.gradle     if your gradle is higher then 3.5.0 you can take this error.

**Comment by mtellect** [comment]
Related to https://github.com/mtellect/CameraDeepAR/issues/24#issue-1091689008

**Comment by jpetro416** [comment]
This is not a solution at all, most of us are running 4.2 gradle
