### ISSUE TITLE
the Package has problems with latest gradle-7.3.3 version , and here what i get 

### ISSUE THREAD

**Issue by bermohmtnm** [mtellect/CameraDeepAR#35]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':camera_deep_ar:bundleDebugAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':camera_deep_ar:bundleDebugAar'
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\camera_deep_ar-0.0.2+3\android\lib\deepar0.aar

**Comment by mtellect** [comment]
related to https://github.com/mtellect/CameraDeepAR/issues/24#issue-1091689008

kindly check the branch dev/example to see implementation

**Comment by bermohmtnm** [comment]
Yes , i used old version of gradle then it is work , but it is not work
with latest version

‫في الثلاثاء، 25 يناير 2022 في 4:38 م تمت كتابة ما يلي بواسطة ‪Maugost‬‏ <‪
***@***.***‬‏>:‬

**Comment by bermohmtnm** [comment]
nothing related with dev/example 😊

‫في الأربعاء، 26 يناير 2022 في 1:50 ص تمت كتابة ما يلي بواسطة ‪Mohammed
Hamdan‬‏ ***@***.***‬‏>:‬
