### ISSUE TITLE
Regarding Dependency configuration

### ISSUE THREAD

**Issue by Fenillad-23** [mtellect/CameraDeepAR#36]
i want to create AR based application for that i tried to use this code but there is one error occurs 

Error:-
 Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find :deepar:.
     Required by:
         project :app > project :camera_deep_ar

**Comment by Hi99simon** [comment]
Could someone write another plugin for deepar? This plugin seems not maintained well...

**Comment by mtellect** [comment]
> Could someone write another plugin for deepar? This plugin seems not maintained well...

Did you follow the example on the Dev branch?
Did you run the example on the Dev branch and it failed to install?

**Comment by mtellect** [comment]
Did you follow the example on the Dev branch?

**Comment by mtellect** [comment]
Hi, if you do want to use this plugin set the following:

Your project build.gradle classpath : 

classpath 'com.android.tools.build:gradle:3.5.0'

set your app.gradle to:

compileSdkVersion 29
minSdkVersion 21
targetSdkVersion 29

set your gradle/wrapper/gradle-wrapper.properties to:
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

this is a customized library for a particular feature i freely open-sourced!
