### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Vvimal27** [mtellect/CameraDeepAR#4]
Flutter app works fine in debug mode but in release mode app crashes

**Comment by JoergPf** [comment]
Hi, were you able to fix this?

**Comment by JoergPf** [comment]
Same to me, I got this error running `flutter build ipa`

/Users/username/Frameworks/flutter/.pub-cache/hosted/pub.dartlang.org/camera_deep_ar-0.0.1/ios/DeepAR.framework/DeepAR (2
    slices)
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_CameraController", referenced from:
          objc-class-ref in SwiftCameraDeepArPlugin.o
      "_OBJC_CLASS_$_DeepAR", referenced from:
          objc-class-ref in SwiftCameraDeepArPlugin.o
      "_OBJC_CLASS_$_ARView", referenced from:
          objc-class-ref in SwiftCameraDeepArPlugin.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by JoergPf** [comment]
Found the Problem: CameraDeepAR needs min iOS 11

**Comment by YaraEslam** [comment]
> Flutter app works fine in debug mode but in release mode app crashes

same here, have you solved it?

**Comment by mtellect** [comment]
> > Flutter app works fine in debug mode but in release mode app crashes
> 
> same here, have you solved it?

Resolved?

**Comment by Praveen-1123** [comment]
> Flutter app works fine in debug mode but in release mode app crashes

I faced the same issue and I fixed the issue by changing the proguard-rules.txt to proguard-rules.pro 
It worked on my side hope this will be helpful.
Thanks.

**Comment by mtellect** [comment]
Please check 0.0.2+2 and ReOpen if the issue persist
