### ISSUE TITLE
License check failed

### ISSUE THREAD

**Issue by apoorvpandey0** [mtellect/CameraDeepAR#5]
- I have set the minimumSdkVersion to 19
- Given the permissions correctly in the AndroidManifest.xml
- Set up the proguard-android.txt file correctly
- And used the sample code given in the docs
- I have generated my API key and have pasted it in the android key, I have left the iOS key as it is since I'm not testing on iOS.
The app opens up but simply says License check failed please verify your key

**Comment by mtellect** [comment]
Please check 0.0.2+2 and ReOpen if the issue persist
