### ISSUE TITLE
Where to put custom masks?

### ISSUE THREAD

**Issue by JoergPf** [mtellect/CameraDeepAR#6]
Hi, thanks for this great package! How do I use a custom mask? 
Thanks!

**Comment by JoeMan97** [comment]
I believe isn't posible to use custom masks at the moment, but I just wanted to know if it'll be possible on the near future.

**Comment by lucasvps** [comment]
Anyone find a way to do that?

**Comment by mtellect** [comment]
Hello, sorry for the delay in response.
i have an update coming soon , i'd put this issue into consideration

**Comment by Praveen-1123** [comment]
> Anyone find a way to do that?

You can define a variable with a list of masks and define them in the supportedMasks field.

List<Masks> supportedMasks = [
    Masks.none,
    Masks.aviators, //glass
    Masks.bigmouth, //big mouth
    Masks.dalmatian, // puppy
    Masks.bcgSeg, //flowers
    Masks.look2, //black bear
    Masks.fatify, //lion
    Masks.grumpycat, //cigarate
    Masks.mudMask, //sleepingmask
    Masks.obama, //fat face
    Masks.slash, //makeup
    Masks.smallface, //sherlock
  ];

make sure your camera mode is set to masks.
Working for me,
Thanks.

**Comment by buraktuntas** [comment]
> Hello, sorry for the delay in response.
> i have an update coming soon , i'd put this issue into consideration

When can you update for this topic?

**Comment by mtellect** [comment]
Please check 0.0.2+2 
Check the example project
Support for custom effects added
