### ISSUE TITLE
Execution failed for task ':camera_deep_ar:bundleDebugAar'.

### ISSUE THREAD

**Issue by bjmcallister** [mtellect/CameraDeepAR#62]
> Error while evaluating property 'hasLocalAarDeps' of task ':camera_deep_ar:bundleDebugAar'
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :camera_deep_ar project caused this error: [/Users/name/development/flutter/.pub-cache/hosted/pub.dartlang.org/camera_deep_ar-0.0.2]()+3[/android/lib/deepar0.aar]()

Occurs on Android whenever using a gradle version ~ (> 3.5.0). iOS has no issues, but this prevents us from using Amplify AWS which requires 4.1.0+ from my research.

**Comment by KalanaPerera** [comment]
I've fixed this: on my Fork - 
commit: https://github.com/KalanaPerera/FlutterDeepAR/commit/407b8917080bc480e14ca3fc5dab883167174c1e

Used Method: https://github.com/siyehua/flutter_aar

Hope this helps

**Comment by bjmcallister** [comment]
Helped a ton! Thank you!
