### ISSUE TITLE
Could not open camera device. Could be used by another process. Camera issue.

### ISSUE THREAD

**Issue by whumpentertainment** [mtellect/CameraDeepAR#9]
I'm facing issue while opening camera (Could not open camera device. Could be used by another process.)

Anyone know how to resolve it.

Thanks for advance.

**Comment by utkarshsharma2922** [comment]
@whumpentertainment You can request the permission for camera before the camera screen is opened to bypass this issue .

**Comment by whumpentertainment** [comment]
@utkarshsharma2922 i already did this but i creates issues when i use back camera.

**Comment by mtellect** [comment]
Please check 0.0.2+2 and ReOpen if the issue persist
